name: release-actions
on:
  push:
    tags:
      - v2
      - v2.*
      - v2.*.*
  pull_request:
    tags:
      - v2
      - v2.*
      - v2.*.*
  release:
    types:
      - created
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: yarn install
      - run: yarn build
      - run: yarn coverage
      - run: yarn examples:build
      - run: yarn lerna:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: yarn lerna:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
