name: release-actions
on:
  push:
    branches:
      - main
  release:
    types:
      - created
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registyr-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn build
      - run: yarn coverage
      - run: yarn examples:build
      - run: npm config set @virtualstate:registry "https://registry.npmjs.org/"
      - run: npm config set "//registry.npmjs.org/:_authToken" "$NODE_AUTH_TOKEN"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      - run: yarn lerna:publish
        if: ${{ startsWith(github.head_commit.message, 'v2.') }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm config set @virtualstate:registry "https://npm.pkg.github.com/"
      - run: npm config set "//npm.pkg.github.com/:_authToken" "$NODE_AUTH_TOKEN"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn lerna:publish
        if: ${{ startsWith(github.head_commit.message, 'v2.') }}
