name: release-actions
on:
  push:
    branches:
      - main
  release:
    types:
      - created
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registyr-url: 'https://registry.npmjs.org'
      - run: yarn install
      - run: yarn build
      - run: yarn coverage
      - run: yarn examples:build
      - name: Package Registry Publish - npm
        run: |
          npm set "registry=https://registry.npmjs.org/"
          npm set "@virtualstate:registry=https://registry.npmjs.org/"
          npm set "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN"
          yarn lerna:publish
        continue-on-error: true
        env:
          YARN_TOKEN: ${{ secrets.YARN_TOKEN }}
          NPM_TOKEN: ${{ secrets.YARN_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Package Registry Publish - GitHub
        run: |
          npm set "registry=https://npm.pkg.github.com/"
          npm set "@virtualstate:registry=https://npm.pkg.github.com/"
          npm set "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN"
          yarn lerna:publish
        env:
          YARN_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
